-- Library room booking - demo data
--
-- Run after database/schema.sql:
--
--   mysql -u root -p < database/seed.sql
--
-- No user accounts are seeded. Passwords are argon2id hashes generated by the
-- API, so accounts are created by registering in the app; the README explains
-- how to promote one to lecturer or staff afterwards.

USE `library_room_booking`;

INSERT INTO `time_slot` (`slot_id`, `start_time`, `end_time`) VALUES
  (1, '08:00:00', '10:00:00'),
  (2, '10:00:00', '12:00:00'),
  (3, '13:00:00', '15:00:00'),
  (4, '15:00:00', '17:00:00');

-- image is left empty: room photos are uploaded through the staff screens and
-- stored in the server's uploads directory. The app falls back to a bundled
-- placeholder asset until a photo is set.
INSERT INTO `room` (`room_name`, `room_status`, `capacity`, `description`) VALUES
  ('Study Room A',      1,  6, 'Quiet space with desks and power outlets for focused work.'),
  ('Study Room B',      1,  5, 'Small group room suited to pair work.'),
  ('Study Room C',      1,  6, 'Calm area for individual or group study.'),
  ('Study Room D',      1,  8, 'Larger study room with a whiteboard.'),
  ('Multimedia Room A', 1, 11, 'Equipped with AV tools for presentations and media work.'),
  ('Multimedia Room B', 1, 15, 'Tech-ready space for presentations.'),
  ('Multimedia Room C', 1, 16, 'Interactive room for producing digital content.'),
  ('Meeting Room A',    1, 10, 'Meeting table and ergonomic seating for long sessions.'),
  ('Meeting Room B',    1,  9, 'Versatile room with audiovisual equipment.'),
  ('Meeting Room C',    0, 10, 'Currently offline for maintenance.');
